name: cxgenie
description: The cxgenie Flutter Package seamlessly integrates https://cxgenie.ai cutting-edge Conversational AI and NLP capabilities into Flutter apps.
version: 2.4.16
homepage: https://cxgenie.ai

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  chewie: ^1.8.1
  flutter_form_builder: ^9.3.0
  flutter_portal: ^1.1.4
  flutter_svg: ^2.0.10
  flutter_widget_from_html_core: ^0.15.1
  form_builder_validators: ^10.0.1
  http: ^1.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  linkify: ^5.0.0
  logger: ^2.3.0
  provider: ^6.1.2
  socket_io_client: ^2.0.3+1
  url_launcher: ^6.3.0
  uuid: ^4.4.0
  video_player: ^2.8.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0

flutter:
  assets:
    - ./images/
