name: cxgenie
description: The cxgenie Flutter Package seamlessly integrates https://cxgenie.ai cutting-edge Conversational AI and NLP capabilities into Flutter apps.
version: 2.3.5
homepage: https://cxgenie.ai

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.1.1
  flutter_svg: ^2.0.7
  form_builder_validators: ^9.1.0
  http: ^1.1.0
  image_picker: ^1.0.4
  intl: ^0.18.1
  modal_bottom_sheet: ^2.1.2
  provider: ^6.0.5
  socket_io_client: ^2.0.3+1
  json_annotation: ^4.8.1
  flutter_custom_tab_bar: ^1.2.1
  flutter_portal: ^1.1.4
  flutter_linkify: ^6.0.0
  url_launcher: ^6.2.3
  linkify: ^5.0.0
  flutter_html: 3.0.0-alpha.6
  flutter_html_iframe: ^3.0.0-alpha.3
  uuid: ^4.2.2
  video_player: ^2.8.2
  video_player_platform_interface: ^6.2.2
  chewie: ^1.7.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  assets:
    - ./images/
